include(FetchContent)

function(git_fetch package fetch_version_or_branch source)
    message(STATUS "Fetch ${package} ${fetch_version} from ${source}")
    FetchContent_Declare(${package} GIT_REPOSITORY ${source} GIT_TAG ${fetch_version})
    FetchContent_GetProperties(${package})
    if (NOT "${package}_POPULATED")
        FetchContent_Populate(${package})
        add_subdirectory("${${package}_SOURCE_DIR}" "${${package}_BINARY_DIR}")
    endif()
    set(${package}_FOUND ON PARENT_SCOPE)
    set("${package}_SOURCE_DIR" "${${package}_SOURCE_DIR}" PARENT_SCOPE)
    set("${package}_BINARY_DIR" "${${package}_BINARY_DIR}" PARENT_SCOPE)
endfunction()
